apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\joris\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cockatoo-accounts-api
  name: cockatoo-accounts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cockatoo-accounts-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\joris\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cockatoo-accounts-api
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: DB_ACCOUNTS_HOST

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: DB_ACCOUNTS_DATABASE

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: DB_ACCOUNTS_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: DB_ACCOUNTS_PASSWORD

            - name: BETTERSTACK_SOURCETOKEN
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: BETTERSTACK_SOURCETOKEN

            - name: BETTERSTACK_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: BETTERSTACK_ENDPOINT

            - name: COCKATOO_Q
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: COCKATOO_Q

            - name: COCKATOO_Q_USERNAME_TOPIC
              valueFrom:
                secretKeyRef:
                  name: cockatoo-global-secret
                  key: COCKATOO_Q_USERNAME_TOPIC

          image: theartcher/cockatoo-accounts-microservice
          name: cockatoo-accounts-api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
